### ISSUE TITLE
Countdown in the start not work properly

### ISSUE THREAD

**Issue by badarshahzad** [HanSolo/tilesfxdemo#1]
I was testing and learning about tilesfx and found a random behaviour in Countdown.java.
https://youtu.be/h8bXSnJ2ugw

**Comment by HanSolo** [comment]
Hi there,
Well that is no random behavior but the effect that you saw is based on the time it takes to flip from one number to another. So it simply takes some time before the FlipTileSkin flipped through all characters until it is up to date. If you wait some time you will see that from a certain moment on it works properly. If you take a look at a real split flap display you will see that you can't simply change from one to another character but you have to flip through all characters until you reach the one you are looking for and that is exactly what you see here :)

Cheers,

Gerrit

**Comment by badarshahzad** [comment]
Wow :open_mouth:  that's awesome its mean the quickly flip is feature to show that how it meets the exactly above one. :+1:  :wave:
